<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;color:#14213d;font:12px/1.45 DejaVu Sans,sans-serif}.page{position:relative;min-height:297mm;padding-bottom:28mm}.header{display:table;width:100%;padding:12mm 15mm 9mm;background:#102858;color:#fff}.header-left,.header-right{display:table-cell;vertical-align:middle}.header-right{width:34%;text-align:right}.logo{width:48px;height:48px;margin-right:11px;vertical-align:middle}.brand{display:inline-block;vertical-align:middle}.brand strong{display:block;font-size:18px;letter-spacing:.5px}.brand small{color:#e6bd4c;font-size:9px;letter-spacing:1.4px;text-transform:uppercase}.doc-type{font-size:22px;font-weight:bold;letter-spacing:2px}.doc-number{margin-top:4px;color:#e6bd4c;font-size:10px;font-weight:bold}.accent{height:4px;background:#d9ad3d}.content{padding:9mm 15mm 0}.meta{display:table;width:100%;margin-bottom:7mm}.meta-col{display:table-cell;width:50%;vertical-align:top}.box{min-height:79px;padding:10px 13px;border-left:3px solid #d9ad3d;border-radius:4px;background:#f5f7fb}.label{color:#71809c;font-size:8px;font-weight:bold;letter-spacing:1px;text-transform:uppercase}.value{margin-top:4px;color:#102858;font-size:12px;font-weight:bold}.sub{margin-top:2px;color:#56627a;font-size:10px}.info{display:table;width:100%;margin-bottom:7mm;padding:10px 13px;border-radius:5px;background:#f0f3f8}.info-cell{display:table-cell;width:33.33%}.info-cell strong{display:block;margin-top:2px;color:#102858}table.items{width:100%;border-collapse:collapse}.items th{padding:9px 11px;background:#102858;color:#fff;font-size:9px;letter-spacing:.5px;text-align:left;text-transform:uppercase}.items th.num,.items td.num{text-align:right}.items td{padding:10px 11px;border-bottom:1px solid #e1e6ef}.items tbody tr:nth-child(even){background:#fafbfd}.kind{color:#77839a;font-size:9px}.totals{width:42%;margin:7mm 0 7mm auto;border-collapse:collapse}.totals td{padding:6px 8px}.totals .amount{color:#102858;font-weight:bold;text-align:right}.totals .grand td{padding-top:9px;border-top:2px solid #d9ad3d;font-size:15px;font-weight:bold}.pending{margin-bottom:7mm;padding:10px 13px;border:1px solid #eed89c;border-radius:5px;background:#fff6df;color:#855d11;font-weight:bold}.methods{padding:10px 13px;border-radius:5px;background:#f5f7fb;color:#4f5d75;font-size:10px}.signatures{display:table;width:100%;margin-top:17mm}.signature{display:table-cell;width:50%;padding:0 12mm;text-align:center}.signature div{padding-top:5px;border-top:1px solid #bcc5d5;color:#71809c;font-size:8px;text-transform:uppercase}.footer{position:absolute;right:15mm;bottom:8mm;left:15mm;padding-top:7px;border-top:1px solid #dfe4ed;color:#8490a6;font-size:8px;text-align:center}.footer strong{color:#102858}
</style></head>
<body>
@php($anneeLabel = isset($annee) ? $annee->libelle : 'Année scolaire #'.$facture->annee_scolaire_id)
<div class="page">
<div class="header"><div class="header-left"><img class="logo" src="{{ public_path('images/logo.png') }}" alt="Logo"><span class="brand"><strong>AMBASSADORS SCHOOL</strong><small>Excellence · Foi · Discipline</small></span></div><div class="header-right"><div class="doc-type">FACTURE</div><div class="doc-number">N° {{ $facture->reference }}</div></div></div><div class="accent"></div>
<div class="content">
<div class="meta"><div class="meta-col" style="padding-right:5mm"><div class="box"><div class="label">Facturé à</div><div class="value">{{ $facture->parent_nom }}</div><div class="sub">Parent / responsable de {{ $facture->eleve_nom }}</div><div class="sub">{{ $facture->parent_email }}</div></div></div><div class="meta-col" style="padding-left:5mm"><div class="box"><div class="label">Établissement</div><div class="value">Ambassadors Educational Complex</div><div class="sub">Emana, Bonne Fontaine — Yaoundé, Cameroun</div><div class="sub">no-reply@ambassadors-aec.com</div></div></div></div>
<div class="info"><div class="info-cell"><span class="label">Date d’émission</span><strong>{{ $facture->created_at?->format('d/m/Y') }}</strong></div><div class="info-cell"><span class="label">Année scolaire</span><strong>{{ $anneeLabel }}</strong></div><div class="info-cell"><span class="label">Échéance</span><strong>Avant validation</strong></div></div>
<table class="items"><thead><tr><th>Désignation</th><th class="num">Quantité</th><th class="num">Prix unitaire</th><th class="num">Montant</th></tr></thead><tbody>@foreach($facture->lignes as $ligne)<tr><td>{{ $ligne->libelle }}<div class="kind">{{ $ligne->obligatoire ? 'Frais obligatoire' : 'Frais optionnel choisi' }}</div></td><td class="num">1</td><td class="num">{{ number_format((float)$ligne->montant,0,',',' ') }} FCFA</td><td class="num"><strong>{{ number_format((float)$ligne->montant,0,',',' ') }} FCFA</strong></td></tr>@endforeach</tbody></table>
@php($parGroupe = $facture->lignes->groupBy(fn ($ligne) => $ligne->groupe?->code ?? (in_array($ligne->type_frais, ['inscription', 'scolarite'], true) ? 'scolarite' : 'autres'))->map->sum('montant'))
<table class="totals"><tr><td>Frais de scolarité</td><td class="amount">{{ number_format((float)($parGroupe['scolarite'] ?? 0),0,',',' ') }} FCFA</td></tr><tr><td>Autres frais</td><td class="amount">{{ number_format((float)($parGroupe['autres'] ?? 0),0,',',' ') }} FCFA</td></tr><tr class="grand"><td>Total à payer</td><td class="amount">{{ number_format((float)$facture->montant_total,0,',',' ') }} FCFA</td></tr></table>
<div class="pending">EN ATTENTE DE PAIEMENT — Le reçu officiel sera envoyé après contrôle du versement par la Comptable.</div><div class="methods"><strong>Modes acceptés :</strong> espèces à la caisse · virement bancaire · Mobile Money (MTN / Orange). Indiquez la référence <strong>{{ $facture->reference }}</strong> lors du paiement.</div>
<div class="signatures"><div class="signature"><div>Signature du parent</div></div><div class="signature"><div>Cachet & signature — Comptabilité</div></div></div>
</div><div class="footer"><strong>Ambassadors Educational Complex</strong> — Yaoundé, Cameroun<br>Cette facture provisoire ne constitue pas une preuve de paiement.</div></div>
</body></html>
