<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;color:#14213d;font:11px/1.45 DejaVu Sans,sans-serif}.page{position:relative;min-height:297mm;padding-bottom:27mm}.header{display:table;width:100%;padding:11mm 15mm 8mm;background:#102858;color:#fff}.header-left,.header-right{display:table-cell;vertical-align:middle}.header-right{width:36%;text-align:right}.logo{width:48px;height:48px;margin-right:11px;vertical-align:middle}.brand{display:inline-block;vertical-align:middle}.brand strong{display:block;font-size:18px;letter-spacing:.5px}.brand small{color:#e6bd4c;font-size:9px;letter-spacing:1.4px;text-transform:uppercase}.doc-type{font-size:20px;font-weight:bold;letter-spacing:2px}.doc-number{color:#e6bd4c;font-size:9px;font-weight:bold}.confirmed{padding:8px;border-top:4px solid #d9ad3d;border-bottom:1px solid #afd9bd;background:#e9f7ee;color:#19703a;font-weight:bold;letter-spacing:.6px;text-align:center}.content{padding:8mm 15mm 0}.meta{display:table;width:100%;margin-bottom:6mm}.meta-col{display:table-cell;width:50%;vertical-align:top}.box{min-height:72px;padding:9px 12px;border-left:3px solid #269452;border-radius:4px;background:#f5f7fb}.label{color:#71809c;font-size:8px;font-weight:bold;letter-spacing:1px;text-transform:uppercase}.value{margin-top:3px;color:#102858;font-size:12px;font-weight:bold}.sub{margin-top:2px;color:#56627a;font-size:9px}.info{display:table;width:100%;margin-bottom:6mm;padding:9px 11px;border-radius:5px;background:#f0f3f8}.info-cell{display:table-cell;width:25%}.info-cell strong{display:block;margin-top:2px;color:#102858}table.items{width:100%;border-collapse:collapse}.items th{padding:8px 10px;background:#102858;color:#fff;font-size:8px;letter-spacing:.5px;text-align:left;text-transform:uppercase}.items th.num,.items td.num{text-align:right}.items td{padding:9px 10px;border-bottom:1px solid #e1e6ef}.items tbody tr:nth-child(even){background:#fafbfd}.totals{width:43%;margin:6mm 0 6mm auto;border-collapse:collapse}.totals td{padding:5px 8px}.totals .amount{color:#102858;font-weight:bold;text-align:right}.totals .balance td{padding-top:8px;border-top:2px solid #269452;font-size:14px;font-weight:bold}.transaction{padding:10px 12px;border-radius:5px;background:#f5f7fb}.transaction table{width:100%;margin-top:5px}.transaction td{padding:2px 0}.transaction td:first-child{width:42%;color:#71809c}.signatures{display:table;width:100%;margin-top:18mm}.signature{display:table-cell;width:50%;padding:0 12mm;text-align:center}.signature div{padding-top:5px;border-top:1px solid #bcc5d5;color:#71809c;font-size:8px;text-transform:uppercase}.footer{position:absolute;right:15mm;bottom:8mm;left:15mm;padding-top:7px;border-top:1px solid #dfe4ed;color:#8490a6;font-size:8px;text-align:center}.footer strong{color:#102858}
</style></head>
<body>
@php
$lignes=collect($contexte['lignes']??[['libelle'=>'Paiement scolaire','montant'=>(float)$paiement->montant]]);$total=(float)($contexte['montant_total']??$paiement->montant);$mode=ucfirst(str_replace('_',' ',$paiement->mode));
@endphp
<div class="page"><div class="header"><div class="header-left"><img class="logo" src="{{ public_path('images/logo.png') }}" alt="Logo"><span class="brand"><strong>AMBASSADORS SCHOOL</strong><small>Excellence · Foi · Discipline</small></span></div><div class="header-right"><div class="doc-type">REÇU D’INSCRIPTION</div><div class="doc-number">N° {{ $paiement->numero_recu }}</div></div></div><div class="confirmed">✓ PAIEMENT CONFIRMÉ — INSCRIPTION ACTIVE</div>
<div class="content"><div class="meta"><div class="meta-col" style="padding-right:5mm"><div class="box"><div class="label">Élève inscrit(e)</div><div class="value">{{ $eleve['prenom'] }} {{ $eleve['nom'] }}</div><div class="sub">Identifiant élève : {{ $eleve['id'] }}</div></div></div><div class="meta-col" style="padding-left:5mm"><div class="box"><div class="label">Payeur / responsable</div><div class="value">{{ $contexte['parent_nom'] ?? 'Non renseigné' }}</div><div class="sub">Facture d’origine : {{ $contexte['facture_reference'] ?? 'Paiement scolaire direct' }}</div></div></div></div>
<div class="info"><div class="info-cell"><span class="label">Date de paiement</span><strong>{{ $paiement->created_at->format('d/m/Y') }}</strong></div><div class="info-cell"><span class="label">Année scolaire</span><strong>{{ $annee->libelle }}</strong></div><div class="info-cell"><span class="label">Mode</span><strong>{{ $mode }}</strong></div><div class="info-cell"><span class="label">Encaissé par</span><strong>{{ $paiement->encaisseur?->name ?? 'Comptabilité' }}</strong></div></div>
<table class="items"><thead><tr><th>Désignation</th><th class="num">Montant dû</th><th class="num">Montant payé</th></tr></thead><tbody>@foreach($lignes as $ligne)<tr><td>{{ $ligne['libelle'] }}</td><td class="num">{{ number_format((float)$ligne['montant'],0,',',' ') }} FCFA</td><td class="num"><strong>{{ number_format((float)$ligne['montant'],0,',',' ') }} FCFA</strong></td></tr>@endforeach</tbody></table>
<table class="totals"><tr><td>Total dû</td><td class="amount">{{ number_format($total,0,',',' ') }} FCFA</td></tr><tr><td>Total payé</td><td class="amount">{{ number_format((float)$paiement->montant,0,',',' ') }} FCFA</td></tr><tr class="balance"><td>Solde restant</td><td class="amount">{{ number_format(max(0,$total-(float)$paiement->montant),0,',',' ') }} FCFA</td></tr></table>
<div class="transaction"><div class="label">Référence de la transaction</div><table><tr><td>Référence du paiement</td><td><strong>{{ $paiement->reference_mobile_money ?: ($contexte['reference_transaction'] ?? 'Paiement en espèces') }}</strong></td></tr><tr><td>Facture provisoire d’origine</td><td><strong>{{ $contexte['facture_reference'] ?? '—' }}</strong></td></tr><tr><td>Statut de l’inscription</td><td><strong>{{ $contexte['statut_inscription'] ?? 'Paiement validé' }}</strong></td></tr></table></div>
<div class="signatures"><div class="signature"><div>Signature du parent</div></div><div class="signature"><div>Cachet & signature — Comptabilité</div></div></div></div><div class="footer"><strong>Ambassadors Educational Complex</strong> — Emana, Bonne Fontaine, Yaoundé, Cameroun<br>Ce reçu fait foi de paiement — Document à conserver pour toute réclamation ultérieure.</div></div>
</body></html>
